[package]
name = "yew-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "^0.19"
serde = {version = "1.0.129", features = ["derive"]}
wasm-bindgen-futures = "0.4.33"
reqwasm = "0.5.0"